# This config may be overridden by creating a gulp-config--custom.yml file
css:
  enabled: true
  src:
    - sass/**/*.scss
  vendor:
    - sass/vendor/**/*.css
  dest: dist/
  flattenDestOutput: true
  lint:
    enabled: true
    failOnError: true
    # Add to the main src glob - useful for exclusions with `!`
    extraSrc:
#      - '!excluded-file.scss'
  # enables additional debugging information in the output file as CSS comments - only use when necessary
  sourceComments: false
  sourceMapEmbed: false
  # tell the compiler whether you want 'expanded' or 'compressed' output code
  outputStyle: compressed
  autoPrefixerBrowsers: # https://github.com/ai/browserslist#queries
    - last 2 versions
    - IE >= 9
  includePaths:
    - ./node_modules
  sassdoc: # http://sassdoc.com
    enabled: true
    dest: public/sassdoc
    verbose: false
    basePath: https://bitbucket.org/ietwebdev/article-26-backpack-pattern-lab/src/master/source/sass
#    exclude:
#      - file.scss
    theme: default
    sort: # http://sassdoc.com/customising-the-view/#sort
      - file
      - group
      - line<

js:
  enabled: true
  src:
    - js/vendor/**/*.js
    - js/**/*.js
#    - '!excluded-file.js'
  dest: dist/
  destName: scripts.js
  sourceMapEmbed: false
  uglify: true
  babel: true
  preserveLicense: false
  eslint:
    enabled: false
    failAfterError: true
    # Add to the main src glob - useful for exclusions with `!`
    extraSrc:
      - '!js/vendor/**/*.js'

nodeFiles:
  enabled: true
  dir: node_modules
  includePaths:
    - node_modules/singularitygs/stylesheets
    - node_modules/breakpoint-sass/stylesheets
    - node_modules/sass-toolkit/stylesheets
    - node_modules/sass-burger
    - node_modules/normalize-scss/sass
#  excludeDist:
#    - /excluded-file.js

bowerFiles:
  enabled: false
  dir: bower_components
#  includePaths:
#    - bower_components/singularity/stylesheets

browserSync:
  enabled: false
  port: 3050
  watchFiles:
#    - 'public/**/*.html'
#  domain: mydomain.local # Change this in the local config file
  baseDir: ./
  startPath: '/'
  openBrowserAtStart: true
  # requires above to be true; allows non-default browser to open
  browser:
    - Google Chrome
  # Tunnel the Browsersync server through a random Public URL
  # -> http://randomstring23232.localtunnel.me
#  tunnel: ucdfrontend
  reloadDelay: 50
  reloadDebounce: 750

# This is the destination of the CMS theme these source files will be ported to
themeSync:
  enabled: false
  newsite: false
  src: false
  dest: ../theme/ # This should be overridden per custom install
  sassSrc: source/sass/
  sassDest: sass/1_pattern_lab/
  jsSrc: source/js/
  jsDest: js/pattern_lab/
  imagesSrc: source/images/
  imagesDest: images/

# Pattern Lab configuration
patternLab:
  enabled: false
  imagesSrc: source/images/
  imagesDest: public/images/
