extends: stylelint-config-sass-guidelines

rules:
  max-nesting-depth:
    - 4
    -
      ignore:
        - blockless-at-rules
  rule-empty-line-before: null
  scss/at-mixin-pattern:
    - "^[a-z]+(([a-z0-9-]|__)+[a-z0-9]+)?$"
  scss/percent-placeholder-pattern: null
  selector-class-pattern:
    - "^([a-z0-9\\-]|__)+$"
    -
      message: "Selector should be written in lowercase with BEM or hyphens (selector-class-pattern)"
  selector-max-compound-selectors: null
  selector-pseudo-element-colon-notation: null
  string-quotes: double
